### ISSUE TITLE
Put on PyPI?

### ISSUE THREAD

**Issue by tobias47n9e** [elad661/flatpak-pypi#1]
Is it planned to put this tool on PyPI? Can't find it there at the moment.

**Comment by elad661** [comment]
No, this is probably not going to be on PyPi.

It's a prototype quality, and someone has reimplemented this idea inside [flatpak-builder-tools](https://github.com/flatpak/flatpak-builder-tools), so that's what people should probably be using instead of my tool.

**Comment by tobias47n9e** [comment]
Thanks for the info. I will try the other tool in that case.
